[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "autopep8>=2.3.2",
    "black>=25.1.0",
    "isort>=6.0.1",
    "streamlit>=1.45.0",
]
